# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: true
cache: packages

r_packages:
  - backports
  - remotes
  - devtools

r:
  - oldrel
  - release
  - devel

os:
  - linux
  - osx

matrix:
  exclude:
    - r: devel
      os: osx

after_success:
 - Rscript -e 'covr::codecov()'
